<?php
require_once __DIR__ . '/inc/config.php'; require_once __DIR__ . '/inc/auth.php'; require_admin();
$orders = read_orders(); $message = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $index = isset($_POST['index']) ? (int)$_POST['index'] : -1;
    if ($_POST['action'] === 'delete' && isset($orders[$index])) {
        $deleted = read_orders(DELETED_ORDERS_FILE); $deleted[] = $orders[$index]; save_orders($deleted, DELETED_ORDERS_FILE); array_splice($orders, $index, 1); save_orders($orders); $message = 'Order deleted.';
    } elseif ($_POST['action'] === 'status' && isset($orders[$index])) {
        $orders[$index]['status'] = $_POST['status'] ?? 'Pending'; save_orders($orders); $message = 'Status updated.';
    } elseif ($_POST['action'] === 'clear') { save_orders([]); $orders = []; $message = 'All orders cleared.'; }
}
if (isset($_GET['export']) && $_GET['export'] === 'csv') { header('Content-Type: text/csv'); header('Content-Disposition: attachment; filename="orders.csv"'); $out=fopen('php://output','w'); fputcsv($out,['Order ID','Status','Time','Customer','Items','Quantity','Total','Table','Payment']); foreach($orders as $o) fputcsv($out,[$o['orderId']??'', $o['status']??'', $o['timestamp']??'', $o['customer']??'', $o['name']??'', $o['items'][0]['qty']??1, $o['price']??0, $o['tableNumber']??'', $o['paymentOption']??'']); fclose($out); exit; }
admin_header('Admin Orders');
?>
<section class="admin-panel"><h2>Orders</h2><?php if ($message): ?><p class="success-message"><?=e($message)?></p><?php endif; ?><div class="admin-actions"><a class="btn" href="admin_change_pass.php">Change password</a><a class="btn" href="admin_restore.php">Restore deleted</a><a class="btn" href="bill.php">Print bill</a><a class="btn" href="admin.php?export=csv">Export CSV</a><form method="post"><input type="hidden" name="action" value="clear"><button class="btn btn-danger" onclick="return confirm('Clear every order?')">Clear all</button></form></div><?php if (!$orders): ?><p>No orders yet.</p><?php else: ?><div class="orders-table-wrap"><table class="orders-table"><thead><tr><th>#</th><th>Order ID</th><th>Customer</th><th>Items / Qty</th><th>Total</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($orders as $i=>$o): ?><tr><td><?=($i+1)?></td><td><?=e($o['orderId']??'Older order')?></td><td><?=e($o['customer']??'')?><br>Table <?=e($o['tableNumber']??'')?></td><td><?=e($o['name']??'')?><?php if(!empty($o['items'])): ?><br><small><?php foreach($o['items'] as $item): ?><?=e($item['name'])?> x <?=e($item['qty']??1)?><br><?php endforeach; ?></small><?php endif; ?></td><td>Rs <?=number_format((float)($o['price']??0),2)?></td><td><form method="post"><input type="hidden" name="action" value="status"><input type="hidden" name="index" value="<?=$i?>"><select name="status"><option <?=($o['status']??'Pending')==='Pending'?'selected':''?>>Pending</option><option <?=($o['status']??'')==='Preparing'?'selected':''?>>Preparing</option><option <?=($o['status']??'')==='Ready'?'selected':''?>>Ready</option><option <?=($o['status']??'')==='Completed'?'selected':''?>>Completed</option></select><button class="btn btn-sm">Save</button></form></td><td><a class="btn btn-sm" href="admin_edit_order.php?i=<?=$i?>">Edit</a><a class="btn btn-sm" href="admin_print_order.php?i=<?=$i?>" target="_blank">Print</a><form method="post"><input type="hidden" name="action" value="delete"><input type="hidden" name="index" value="<?=$i?>"><button class="btn btn-sm btn-danger">Delete</button></form></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section>
<?php admin_footer(); ?>
