<?php
require_once __DIR__ . '/inc/config.php';
require_once __DIR__ . '/inc/auth.php';
require_admin();
$orders = read_orders();
$grandTotal = array_reduce($orders, fn($sum, $order) => $sum + (float)($order['price'] ?? 0), 0);
?>
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Sales summary - Studio Table by Sam</title>
	<style>
		:root{--accent:#e85d04;--ink:#211c18;--line:#eadfd5}*{box-sizing:border-box}body{margin:0;background:#eee8e1;color:var(--ink);font:14px Arial,sans-serif}.report{max-width:850px;margin:32px auto;background:#fff;padding:42px;box-shadow:0 14px 35px rgba(33,28,24,.14)}.brand{display:flex;align-items:center;gap:18px;border-bottom:3px solid var(--accent);padding-bottom:22px}.logo{width:76px;height:76px;object-fit:contain}.brand h1{margin:0;font:700 30px Georgia,serif}.brand p{margin:5px 0 0;color:#777;text-transform:uppercase;letter-spacing:1px;font-size:11px}.report-heading{display:flex;justify-content:space-between;align-items:end;margin:28px 0 14px}.report-heading h2{margin:0;font:700 24px Georgia,serif}.report-heading span{color:#777}table{width:100%;border-collapse:collapse}th{background:var(--ink);color:#fff;text-align:left;padding:12px}td{padding:13px 12px;border-bottom:1px solid var(--line)}th:last-child,td:last-child{text-align:right}.total{margin:22px 0 0 auto;max-width:310px;display:flex;justify-content:space-between;border-top:3px solid var(--accent);padding:14px 0;font-size:21px;font-weight:700;color:var(--accent)}.print-button{display:block;margin:26px auto 0;border:0;background:var(--accent);color:#fff;padding:11px 22px;border-radius:5px;cursor:pointer;font-weight:700}@media print{body{background:#fff}.report{margin:0;box-shadow:none;max-width:none}.print-button{display:none}}
	</style>
</head>
<body><main class="report"><header class="brand"><img class="logo" src="images/logofinal.jpg" alt="Studio Table logo"><div><h1>Studio Table by Sam</h1><p>Restaurant sales summary</p></div></header><section class="report-heading"><h2>All orders</h2><span><?= date('d M Y, H:i') ?></span></section><table><thead><tr><th>#</th><th>Order ID</th><th>Customer</th><th>Items</th><th>Total</th></tr></thead><tbody><?php foreach($orders as $i=>$order): ?><tr><td><?= $i+1 ?></td><td><?= e($order['orderId']??'') ?></td><td><?= e($order['customer']??'') ?></td><td><?= e($order['name']??'') ?></td><td>Rs <?= number_format((float)($order['price']??0),2) ?></td></tr><?php endforeach; ?></tbody></table><div class="total"><span>Grand total</span><span>Rs <?= number_format($grandTotal,2) ?></span></div><button class="print-button" onclick="window.print()">Print sales summary</button></main></body></html>
<?php require_once __DIR__.'/inc/config.php'; require_once __DIR__.'/inc/auth.php'; require_admin(); $orders=read_orders(); $total=array_reduce($orders,fn($s,$o)=>$s+(float)($o['price']??0),0); ?><!doctype html><html><head><meta charset="utf-8"><title>Restaurant Bill</title><style>body{font:16px Arial;padding:30px}.bill{max-width:700px;margin:auto}.bill h1{color:#e85d04}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #ddd;text-align:left}</style></head><body><div class="bill"><h1>Studio Table by Sam</h1><h2>All Orders Bill</h2><table><tr><th>Order</th><th>Customer</th><th>Items</th><th>Total</th></tr><?php foreach($orders as $o):?><tr><td><?=e($o['orderId']??'')?></td><td><?=e($o['customer']??'')?></td><td><?=e($o['name']??'')?></td><td>Rs <?=number_format((float)($o['price']??0),2)?></td></tr><?php endforeach;?></table><h2>Grand total: Rs <?=number_format($total,2)?></h2><button onclick="print()">Print</button></div></body></html>
